apiVersion: 1

datasources:
  - name: InfluxDB-BARNS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: barns
      defaultBucket: logs
      tlsSkipVerify: true
    secureJsonData:
      token: barns-super-secret-token
    editable: false
    isDefault: true

