apiVersion: v1
kind: ConfigMap
metadata:
  name: routine-tasks-config
  namespace: barns
data:
  tasks.json: |
    {
      "automation_test": {
        "steps": [
          {
            "type": "automation",
            "function": "automation_test",
            "params": {}
          }
        ]
      },
      "dispense_milk": {
        "steps": [
          {
            "type": "automation",
            "function": "dispense_milk",
            "params": {}
          }
        ]
      },
      "dispense_sauce": {
        "steps": [
          {
            "type": "automation",
            "function": "dispense_sauce",
            "params": {}
          }
        ]
      },
      "dispense_slush": {
        "steps": [
          {
            "type": "automation",
            "function": "slush_machine",
            "params": {}
          }
        ]
      },
      "dispensese_coffee": {
        "steps": [
          {
            "type": "automation",
            "function": "coffee_machine",
            "params": {}
          }
        ]
      },
      "dispense_ice": {
        "steps": [
          {
            "type": "automation",
            "function": "dispense_ice",
            "params": {
              "cup_size": "7oz"
            }
          }
        ]
      },
      "grind_coffee": {
        "steps": [
          {
            "type": "automation",
            "function": "grinding_machine",
            "params": {
              "shots_number": 1
            }
          }
        ]
      },
      "clean_steam_wand": {
        "steps": [
          {
            "type": "robot",
            "function": "clean_steam_wand",
            "params": {
              "duration": 18
            }
          }
        ]
      },
      "tamper_coffee": {
        "steps": [
          {
            "type": "automation",
            "function": "tampering_machine",
            "params": {}
          }
        ]
      },
      "Validate_Cup": {
        "steps": [
          {
            "type": "validation",
            "function": "cup_detection",
            "params": {}
          }
        ]
      },
      "Calibrate": {
        "steps": [
          {
            "type": "robot",
            "function": "get_machine_position",
            "params": {}
          }
        ]
      },
      "Espresso": {
          "steps": [
          {
            "type": "validation",
            "function": "validate_ingredients",
            "params": {}
          },
          {
            "type": "validation",
            "function": "update_ingredients",
            "params": {}
          },
          {
              "type": "automation",
              "function": "grinding_machine",
              "params": {
              "shots_number": 2
              }
          },
          {
              "type": "robot",
              "function": "unmount",
              "params": {
              "port": "port_3"
              }
          },
          {
              "type": "robot",
              "function": "grinder",
              "params": {
              "portafilter_tool": "double_portafilter"
              }
          },
          {
              "type": "automation",
              "function": "tampering_machine",
              "params": {}
          },
          {
              "type": "robot",
              "function": "tamper",
              "params": {
              "portafilter_tool": "double_portafilter"
              }
          },
          {
              "type": "robot",
              "function": "mount",
              "params": {
              "port": "port_3"
              }
          },
          {
              "type": "automation",
              "function": "coffee_machine",
              "params": {
              "coffee_t": 2,
              "slot_number": 3
              }
          },
          {
            "type": "validation",
            "function": "cup_detection",
            "params": {}
          },
          {
            "type": "robot",
            "function": "dispense_paper_cup",
            "params": {}
          },
          {
              "type": "robot",
              "function": "pick_espresso_pitcher",
              "params": {
                "port": "port_3"
              }
          }
          ]
      }
    }






