flowchart TD
  N0(["START angled__is_valid_angles(**params)"])
  N1(["RETURN bool(angles) and isinstance(angles, (tuple, list)) and len(angles) == 6"])
  N2(["END angled__is_valid_angles"])
  N0 --> N1
  N0 --> N2
