flowchart TD
  N0(["START angled_single_return_espresso_pitcher(**params)"])
  N1(["RETURN angled_return_espresso_pitcher(**params)"])
  N2(["END angled_single_return_espresso_pitcher"])
  N0 --> N1
  N0 --> N2
