aruco_id:
  - id: 1
    name: calibration_tag_1
  - id: 2
    name: calibration_tag_2
  - id: 3
    name: calibration_tag_3
  - id: 4
    name: calibration_tag_4
  - id: 12
    name: single_portafilter
  - id: 11
    name: double_portafilter
  - id: 21
    name: single_portafilter_mount
  - id: 22
    name: double_portafilter_mount
  - id: 41
    name: three_group_espresso
  - id: 31
    name: espresso_grinder
  - id: 16
    name: single_shot_pitcher
  - id: 17
    name: double_shot_pitcher
  - id: 18
    name: left_steam_wand
  - id: 23
    name: portafilter_cleaner
    
