flowchart TD
  N0(["START close_gripper(**params)"])
  N1["Robot call: run_skill('sync')"]
  N2["Robot call: run_skill('set_gripper_position', 255, 255, 255)"]
  N3(["RETURN True"])
  N4(["END close_gripper"])
  N0 --> N1
  N1 --> N2
  N2 --> N3
  N0 --> N4
