apiVersion: v1
kind: Service
metadata:
  name: automation-service
  namespace: barns
  labels:
    app: automation-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: automation-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-service
  namespace: barns
  labels:
    app: automation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation-service
  template:
    metadata:
      labels:
        app: automation-service
    spec:
      imagePullSecrets:
      - name: gcr-json-key
      containers:
      - name: automation-service
        image: me-central2-docker.pkg.dev/qss-development-project/barns/barns-automation:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: url
        - name: PYTHONPATH
          value: "/app"
        - name: DEBUG
          value: "false"
        - name: TELEGRAF_HOST
          value: "telegraf"
        - name: TELEGRAF_PORT
          value: "8094"






